language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t mckeder/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true mckeder/docker-react npm run test -- --coverage